# Generated by Django 6.0.4 on 2026-05-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
