# Generated by Django 6.0.4 on 2026-07-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_rename_create_at_usersubscription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_type',
            field=models.CharField(choices=[('month', '1 Month'), ('six', '6 Months'), ('year', '1 Year')], default='month', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(help_text='Duration in days'),
        ),
    ]
