# Generated by Django 6.0.4 on 2026-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscription_billing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='billing_type',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
