# Generated by Django 6.0.4 on 2026-07-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('memory', 'Memory Forensics'), ('disk', 'Disk Forensics'), ('network', 'Network Analysis'), ('mobile', 'Mobile Forensics')], default='memory', max_length=50),
        ),
    ]
