# Generated by Django 6.0.3 on 2026-04-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('qdrant_point_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='evidence.evidencefile')),
            ],
        ),
    ]
